# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import MY_example_pb2 as MY__example__pb2


class multiplicationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.met = channel.unary_unary(
        '/multiplication/met',
        request_serializer=MY__example__pb2.features.SerializeToString,
        response_deserializer=MY__example__pb2.ans.FromString,
        )


class multiplicationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def met(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_multiplicationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'met': grpc.unary_unary_rpc_method_handler(
          servicer.met,
          request_deserializer=MY__example__pb2.features.FromString,
          response_serializer=MY__example__pb2.ans.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'multiplication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
